// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "aptitude_questions")
public class AptitudeQuestion {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String category;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String question;
    @ElementCollection
    @CollectionTable(name = "aptitude_options", joinColumns = @JoinColumn(name = "question_id"))
    @Column(name = "option_text")
    private List<String> options;
    private int correctAnswer; // index of the correct option
    @Column(columnDefinition = "TEXT")
    private String explanation;
    private int difficultyLevel; // 1=Easy, 2=Medium, 3=Hard


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class AptitudeQuestionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String category;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String question;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<String> options;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int correctAnswer;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String explanation;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int difficultyLevel;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        AptitudeQuestionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder question(final String question) {
            this.question = question;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder options(final List<String> options) {
            this.options = options;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder correctAnswer(final int correctAnswer) {
            this.correctAnswer = correctAnswer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder explanation(final String explanation) {
            this.explanation = explanation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion.AptitudeQuestionBuilder difficultyLevel(final int difficultyLevel) {
            this.difficultyLevel = difficultyLevel;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AptitudeQuestion build() {
            return new AptitudeQuestion(this.id, this.category, this.question, this.options, this.correctAnswer, this.explanation, this.difficultyLevel);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "AptitudeQuestion.AptitudeQuestionBuilder(id=" + this.id + ", category=" + this.category + ", question=" + this.question + ", options=" + this.options + ", correctAnswer=" + this.correctAnswer + ", explanation=" + this.explanation + ", difficultyLevel=" + this.difficultyLevel + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static AptitudeQuestion.AptitudeQuestionBuilder builder() {
        return new AptitudeQuestion.AptitudeQuestionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQuestion() {
        return this.question;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getOptions() {
        return this.options;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCorrectAnswer() {
        return this.correctAnswer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getExplanation() {
        return this.explanation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getDifficultyLevel() {
        return this.difficultyLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuestion(final String question) {
        this.question = question;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOptions(final List<String> options) {
        this.options = options;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCorrectAnswer(final int correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExplanation(final String explanation) {
        this.explanation = explanation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDifficultyLevel(final int difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AptitudeQuestion)) return false;
        final AptitudeQuestion other = (AptitudeQuestion) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getCorrectAnswer() != other.getCorrectAnswer()) return false;
        if (this.getDifficultyLevel() != other.getDifficultyLevel()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$question = this.getQuestion();
        final java.lang.Object other$question = other.getQuestion();
        if (this$question == null ? other$question != null : !this$question.equals(other$question)) return false;
        final java.lang.Object this$options = this.getOptions();
        final java.lang.Object other$options = other.getOptions();
        if (this$options == null ? other$options != null : !this$options.equals(other$options)) return false;
        final java.lang.Object this$explanation = this.getExplanation();
        final java.lang.Object other$explanation = other.getExplanation();
        if (this$explanation == null ? other$explanation != null : !this$explanation.equals(other$explanation)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AptitudeQuestion;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getCorrectAnswer();
        result = result * PRIME + this.getDifficultyLevel();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $question = this.getQuestion();
        result = result * PRIME + ($question == null ? 43 : $question.hashCode());
        final java.lang.Object $options = this.getOptions();
        result = result * PRIME + ($options == null ? 43 : $options.hashCode());
        final java.lang.Object $explanation = this.getExplanation();
        result = result * PRIME + ($explanation == null ? 43 : $explanation.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AptitudeQuestion(id=" + this.getId() + ", category=" + this.getCategory() + ", question=" + this.getQuestion() + ", options=" + this.getOptions() + ", correctAnswer=" + this.getCorrectAnswer() + ", explanation=" + this.getExplanation() + ", difficultyLevel=" + this.getDifficultyLevel() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AptitudeQuestion() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AptitudeQuestion(final Long id, final String category, final String question, final List<String> options, final int correctAnswer, final String explanation, final int difficultyLevel) {
        this.id = id;
        this.category = category;
        this.question = question;
        this.options = options;
        this.correctAnswer = correctAnswer;
        this.explanation = explanation;
        this.difficultyLevel = difficultyLevel;
    }
}
