// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "company_prep_profiles")
public class CompanyPrepProfile {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true)
    private String company;
    @Column(nullable = false)
    private String aptitudeLevel;
    @Column(nullable = false, length = 8)
    private String logoText;
    @Column(nullable = false, length = 32)
    private String brandColor;
    @Column(nullable = false, length = 1024)
    private String roundPattern;
    @Column(nullable = false, length = 1024)
    private String prepPlan;
    private Integer interviewRounds;
    private Integer onlineAssessmentQuestions;
    private Integer codingQuestions;
    private Integer interviewDurationMinutes;
    private Integer displayOrder;
    @OneToMany(mappedBy = "profile", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("displayOrder ASC, id ASC")
    private List<CompanyPrepFocusArea> focusAreas;
    @OneToMany(mappedBy = "profile", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("displayOrder ASC, id ASC")
    private List<CompanyPrepQuestion> askedQuestions;
    @OneToMany(mappedBy = "profile", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("displayOrder ASC, id ASC")
    private List<CompanyPrepRecommendation> recommendedProblems;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static List<CompanyPrepFocusArea> $default$focusAreas() {
        return new ArrayList<>();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static List<CompanyPrepQuestion> $default$askedQuestions() {
        return new ArrayList<>();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static List<CompanyPrepRecommendation> $default$recommendedProblems() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CompanyPrepProfileBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String company;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String aptitudeLevel;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String logoText;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String brandColor;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String roundPattern;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String prepPlan;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer interviewRounds;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer onlineAssessmentQuestions;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer codingQuestions;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer interviewDurationMinutes;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer displayOrder;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean focusAreas$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<CompanyPrepFocusArea> focusAreas$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean askedQuestions$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<CompanyPrepQuestion> askedQuestions$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean recommendedProblems$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<CompanyPrepRecommendation> recommendedProblems$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CompanyPrepProfileBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder company(final String company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder aptitudeLevel(final String aptitudeLevel) {
            this.aptitudeLevel = aptitudeLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder logoText(final String logoText) {
            this.logoText = logoText;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder brandColor(final String brandColor) {
            this.brandColor = brandColor;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder roundPattern(final String roundPattern) {
            this.roundPattern = roundPattern;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder prepPlan(final String prepPlan) {
            this.prepPlan = prepPlan;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder interviewRounds(final Integer interviewRounds) {
            this.interviewRounds = interviewRounds;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder onlineAssessmentQuestions(final Integer onlineAssessmentQuestions) {
            this.onlineAssessmentQuestions = onlineAssessmentQuestions;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder codingQuestions(final Integer codingQuestions) {
            this.codingQuestions = codingQuestions;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder interviewDurationMinutes(final Integer interviewDurationMinutes) {
            this.interviewDurationMinutes = interviewDurationMinutes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder focusAreas(final List<CompanyPrepFocusArea> focusAreas) {
            this.focusAreas$value = focusAreas;
            focusAreas$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder askedQuestions(final List<CompanyPrepQuestion> askedQuestions) {
            this.askedQuestions$value = askedQuestions;
            askedQuestions$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder recommendedProblems(final List<CompanyPrepRecommendation> recommendedProblems) {
            this.recommendedProblems$value = recommendedProblems;
            recommendedProblems$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile.CompanyPrepProfileBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepProfile build() {
            List<CompanyPrepFocusArea> focusAreas$value = this.focusAreas$value;
            if (!this.focusAreas$set) focusAreas$value = CompanyPrepProfile.$default$focusAreas();
            List<CompanyPrepQuestion> askedQuestions$value = this.askedQuestions$value;
            if (!this.askedQuestions$set) askedQuestions$value = CompanyPrepProfile.$default$askedQuestions();
            List<CompanyPrepRecommendation> recommendedProblems$value = this.recommendedProblems$value;
            if (!this.recommendedProblems$set) recommendedProblems$value = CompanyPrepProfile.$default$recommendedProblems();
            return new CompanyPrepProfile(this.id, this.company, this.aptitudeLevel, this.logoText, this.brandColor, this.roundPattern, this.prepPlan, this.interviewRounds, this.onlineAssessmentQuestions, this.codingQuestions, this.interviewDurationMinutes, this.displayOrder, focusAreas$value, askedQuestions$value, recommendedProblems$value, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CompanyPrepProfile.CompanyPrepProfileBuilder(id=" + this.id + ", company=" + this.company + ", aptitudeLevel=" + this.aptitudeLevel + ", logoText=" + this.logoText + ", brandColor=" + this.brandColor + ", roundPattern=" + this.roundPattern + ", prepPlan=" + this.prepPlan + ", interviewRounds=" + this.interviewRounds + ", onlineAssessmentQuestions=" + this.onlineAssessmentQuestions + ", codingQuestions=" + this.codingQuestions + ", interviewDurationMinutes=" + this.interviewDurationMinutes + ", displayOrder=" + this.displayOrder + ", focusAreas$value=" + this.focusAreas$value + ", askedQuestions$value=" + this.askedQuestions$value + ", recommendedProblems$value=" + this.recommendedProblems$value + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CompanyPrepProfile.CompanyPrepProfileBuilder builder() {
        return new CompanyPrepProfile.CompanyPrepProfileBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCompany() {
        return this.company;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAptitudeLevel() {
        return this.aptitudeLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogoText() {
        return this.logoText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBrandColor() {
        return this.brandColor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRoundPattern() {
        return this.roundPattern;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrepPlan() {
        return this.prepPlan;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getInterviewRounds() {
        return this.interviewRounds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getOnlineAssessmentQuestions() {
        return this.onlineAssessmentQuestions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCodingQuestions() {
        return this.codingQuestions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getInterviewDurationMinutes() {
        return this.interviewDurationMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<CompanyPrepFocusArea> getFocusAreas() {
        return this.focusAreas;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<CompanyPrepQuestion> getAskedQuestions() {
        return this.askedQuestions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<CompanyPrepRecommendation> getRecommendedProblems() {
        return this.recommendedProblems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompany(final String company) {
        this.company = company;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAptitudeLevel(final String aptitudeLevel) {
        this.aptitudeLevel = aptitudeLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogoText(final String logoText) {
        this.logoText = logoText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBrandColor(final String brandColor) {
        this.brandColor = brandColor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRoundPattern(final String roundPattern) {
        this.roundPattern = roundPattern;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrepPlan(final String prepPlan) {
        this.prepPlan = prepPlan;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterviewRounds(final Integer interviewRounds) {
        this.interviewRounds = interviewRounds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOnlineAssessmentQuestions(final Integer onlineAssessmentQuestions) {
        this.onlineAssessmentQuestions = onlineAssessmentQuestions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCodingQuestions(final Integer codingQuestions) {
        this.codingQuestions = codingQuestions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterviewDurationMinutes(final Integer interviewDurationMinutes) {
        this.interviewDurationMinutes = interviewDurationMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayOrder(final Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFocusAreas(final List<CompanyPrepFocusArea> focusAreas) {
        this.focusAreas = focusAreas;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAskedQuestions(final List<CompanyPrepQuestion> askedQuestions) {
        this.askedQuestions = askedQuestions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecommendedProblems(final List<CompanyPrepRecommendation> recommendedProblems) {
        this.recommendedProblems = recommendedProblems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CompanyPrepProfile)) return false;
        final CompanyPrepProfile other = (CompanyPrepProfile) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$interviewRounds = this.getInterviewRounds();
        final java.lang.Object other$interviewRounds = other.getInterviewRounds();
        if (this$interviewRounds == null ? other$interviewRounds != null : !this$interviewRounds.equals(other$interviewRounds)) return false;
        final java.lang.Object this$onlineAssessmentQuestions = this.getOnlineAssessmentQuestions();
        final java.lang.Object other$onlineAssessmentQuestions = other.getOnlineAssessmentQuestions();
        if (this$onlineAssessmentQuestions == null ? other$onlineAssessmentQuestions != null : !this$onlineAssessmentQuestions.equals(other$onlineAssessmentQuestions)) return false;
        final java.lang.Object this$codingQuestions = this.getCodingQuestions();
        final java.lang.Object other$codingQuestions = other.getCodingQuestions();
        if (this$codingQuestions == null ? other$codingQuestions != null : !this$codingQuestions.equals(other$codingQuestions)) return false;
        final java.lang.Object this$interviewDurationMinutes = this.getInterviewDurationMinutes();
        final java.lang.Object other$interviewDurationMinutes = other.getInterviewDurationMinutes();
        if (this$interviewDurationMinutes == null ? other$interviewDurationMinutes != null : !this$interviewDurationMinutes.equals(other$interviewDurationMinutes)) return false;
        final java.lang.Object this$displayOrder = this.getDisplayOrder();
        final java.lang.Object other$displayOrder = other.getDisplayOrder();
        if (this$displayOrder == null ? other$displayOrder != null : !this$displayOrder.equals(other$displayOrder)) return false;
        final java.lang.Object this$company = this.getCompany();
        final java.lang.Object other$company = other.getCompany();
        if (this$company == null ? other$company != null : !this$company.equals(other$company)) return false;
        final java.lang.Object this$aptitudeLevel = this.getAptitudeLevel();
        final java.lang.Object other$aptitudeLevel = other.getAptitudeLevel();
        if (this$aptitudeLevel == null ? other$aptitudeLevel != null : !this$aptitudeLevel.equals(other$aptitudeLevel)) return false;
        final java.lang.Object this$logoText = this.getLogoText();
        final java.lang.Object other$logoText = other.getLogoText();
        if (this$logoText == null ? other$logoText != null : !this$logoText.equals(other$logoText)) return false;
        final java.lang.Object this$brandColor = this.getBrandColor();
        final java.lang.Object other$brandColor = other.getBrandColor();
        if (this$brandColor == null ? other$brandColor != null : !this$brandColor.equals(other$brandColor)) return false;
        final java.lang.Object this$roundPattern = this.getRoundPattern();
        final java.lang.Object other$roundPattern = other.getRoundPattern();
        if (this$roundPattern == null ? other$roundPattern != null : !this$roundPattern.equals(other$roundPattern)) return false;
        final java.lang.Object this$prepPlan = this.getPrepPlan();
        final java.lang.Object other$prepPlan = other.getPrepPlan();
        if (this$prepPlan == null ? other$prepPlan != null : !this$prepPlan.equals(other$prepPlan)) return false;
        final java.lang.Object this$focusAreas = this.getFocusAreas();
        final java.lang.Object other$focusAreas = other.getFocusAreas();
        if (this$focusAreas == null ? other$focusAreas != null : !this$focusAreas.equals(other$focusAreas)) return false;
        final java.lang.Object this$askedQuestions = this.getAskedQuestions();
        final java.lang.Object other$askedQuestions = other.getAskedQuestions();
        if (this$askedQuestions == null ? other$askedQuestions != null : !this$askedQuestions.equals(other$askedQuestions)) return false;
        final java.lang.Object this$recommendedProblems = this.getRecommendedProblems();
        final java.lang.Object other$recommendedProblems = other.getRecommendedProblems();
        if (this$recommendedProblems == null ? other$recommendedProblems != null : !this$recommendedProblems.equals(other$recommendedProblems)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CompanyPrepProfile;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $interviewRounds = this.getInterviewRounds();
        result = result * PRIME + ($interviewRounds == null ? 43 : $interviewRounds.hashCode());
        final java.lang.Object $onlineAssessmentQuestions = this.getOnlineAssessmentQuestions();
        result = result * PRIME + ($onlineAssessmentQuestions == null ? 43 : $onlineAssessmentQuestions.hashCode());
        final java.lang.Object $codingQuestions = this.getCodingQuestions();
        result = result * PRIME + ($codingQuestions == null ? 43 : $codingQuestions.hashCode());
        final java.lang.Object $interviewDurationMinutes = this.getInterviewDurationMinutes();
        result = result * PRIME + ($interviewDurationMinutes == null ? 43 : $interviewDurationMinutes.hashCode());
        final java.lang.Object $displayOrder = this.getDisplayOrder();
        result = result * PRIME + ($displayOrder == null ? 43 : $displayOrder.hashCode());
        final java.lang.Object $company = this.getCompany();
        result = result * PRIME + ($company == null ? 43 : $company.hashCode());
        final java.lang.Object $aptitudeLevel = this.getAptitudeLevel();
        result = result * PRIME + ($aptitudeLevel == null ? 43 : $aptitudeLevel.hashCode());
        final java.lang.Object $logoText = this.getLogoText();
        result = result * PRIME + ($logoText == null ? 43 : $logoText.hashCode());
        final java.lang.Object $brandColor = this.getBrandColor();
        result = result * PRIME + ($brandColor == null ? 43 : $brandColor.hashCode());
        final java.lang.Object $roundPattern = this.getRoundPattern();
        result = result * PRIME + ($roundPattern == null ? 43 : $roundPattern.hashCode());
        final java.lang.Object $prepPlan = this.getPrepPlan();
        result = result * PRIME + ($prepPlan == null ? 43 : $prepPlan.hashCode());
        final java.lang.Object $focusAreas = this.getFocusAreas();
        result = result * PRIME + ($focusAreas == null ? 43 : $focusAreas.hashCode());
        final java.lang.Object $askedQuestions = this.getAskedQuestions();
        result = result * PRIME + ($askedQuestions == null ? 43 : $askedQuestions.hashCode());
        final java.lang.Object $recommendedProblems = this.getRecommendedProblems();
        result = result * PRIME + ($recommendedProblems == null ? 43 : $recommendedProblems.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CompanyPrepProfile(id=" + this.getId() + ", company=" + this.getCompany() + ", aptitudeLevel=" + this.getAptitudeLevel() + ", logoText=" + this.getLogoText() + ", brandColor=" + this.getBrandColor() + ", roundPattern=" + this.getRoundPattern() + ", prepPlan=" + this.getPrepPlan() + ", interviewRounds=" + this.getInterviewRounds() + ", onlineAssessmentQuestions=" + this.getOnlineAssessmentQuestions() + ", codingQuestions=" + this.getCodingQuestions() + ", interviewDurationMinutes=" + this.getInterviewDurationMinutes() + ", displayOrder=" + this.getDisplayOrder() + ", focusAreas=" + this.getFocusAreas() + ", askedQuestions=" + this.getAskedQuestions() + ", recommendedProblems=" + this.getRecommendedProblems() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepProfile() {
        this.focusAreas = CompanyPrepProfile.$default$focusAreas();
        this.askedQuestions = CompanyPrepProfile.$default$askedQuestions();
        this.recommendedProblems = CompanyPrepProfile.$default$recommendedProblems();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepProfile(final Long id, final String company, final String aptitudeLevel, final String logoText, final String brandColor, final String roundPattern, final String prepPlan, final Integer interviewRounds, final Integer onlineAssessmentQuestions, final Integer codingQuestions, final Integer interviewDurationMinutes, final Integer displayOrder, final List<CompanyPrepFocusArea> focusAreas, final List<CompanyPrepQuestion> askedQuestions, final List<CompanyPrepRecommendation> recommendedProblems, final LocalDateTime createdAt) {
        this.id = id;
        this.company = company;
        this.aptitudeLevel = aptitudeLevel;
        this.logoText = logoText;
        this.brandColor = brandColor;
        this.roundPattern = roundPattern;
        this.prepPlan = prepPlan;
        this.interviewRounds = interviewRounds;
        this.onlineAssessmentQuestions = onlineAssessmentQuestions;
        this.codingQuestions = codingQuestions;
        this.interviewDurationMinutes = interviewDurationMinutes;
        this.displayOrder = displayOrder;
        this.focusAreas = focusAreas;
        this.askedQuestions = askedQuestions;
        this.recommendedProblems = recommendedProblems;
        this.createdAt = createdAt;
    }
}
