// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "company_prep_focus_areas")
public class CompanyPrepFocusArea {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "profile_id", nullable = false)
    private CompanyPrepProfile profile;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "topic_id", nullable = false)
    private PracticeTopic topic;
    private Integer displayOrder;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CompanyPrepFocusAreaBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private CompanyPrepProfile profile;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PracticeTopic topic;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer displayOrder;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CompanyPrepFocusAreaBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder profile(final CompanyPrepProfile profile) {
            this.profile = profile;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder topic(final PracticeTopic topic) {
            this.topic = topic;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepFocusArea build() {
            return new CompanyPrepFocusArea(this.id, this.profile, this.topic, this.displayOrder);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder(id=" + this.id + ", profile=" + this.profile + ", topic=" + this.topic + ", displayOrder=" + this.displayOrder + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder builder() {
        return new CompanyPrepFocusArea.CompanyPrepFocusAreaBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepProfile getProfile() {
        return this.profile;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeTopic getTopic() {
        return this.topic;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProfile(final CompanyPrepProfile profile) {
        this.profile = profile;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTopic(final PracticeTopic topic) {
        this.topic = topic;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayOrder(final Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CompanyPrepFocusArea)) return false;
        final CompanyPrepFocusArea other = (CompanyPrepFocusArea) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$displayOrder = this.getDisplayOrder();
        final java.lang.Object other$displayOrder = other.getDisplayOrder();
        if (this$displayOrder == null ? other$displayOrder != null : !this$displayOrder.equals(other$displayOrder)) return false;
        final java.lang.Object this$profile = this.getProfile();
        final java.lang.Object other$profile = other.getProfile();
        if (this$profile == null ? other$profile != null : !this$profile.equals(other$profile)) return false;
        final java.lang.Object this$topic = this.getTopic();
        final java.lang.Object other$topic = other.getTopic();
        if (this$topic == null ? other$topic != null : !this$topic.equals(other$topic)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CompanyPrepFocusArea;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $displayOrder = this.getDisplayOrder();
        result = result * PRIME + ($displayOrder == null ? 43 : $displayOrder.hashCode());
        final java.lang.Object $profile = this.getProfile();
        result = result * PRIME + ($profile == null ? 43 : $profile.hashCode());
        final java.lang.Object $topic = this.getTopic();
        result = result * PRIME + ($topic == null ? 43 : $topic.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CompanyPrepFocusArea(id=" + this.getId() + ", profile=" + this.getProfile() + ", topic=" + this.getTopic() + ", displayOrder=" + this.getDisplayOrder() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepFocusArea() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepFocusArea(final Long id, final CompanyPrepProfile profile, final PracticeTopic topic, final Integer displayOrder) {
        this.id = id;
        this.profile = profile;
        this.topic = topic;
        this.displayOrder = displayOrder;
    }
}
