// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "company_prep_questions")
public class CompanyPrepQuestion {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "profile_id", nullable = false)
    private CompanyPrepProfile profile;
    @Column(nullable = false, length = 1024)
    private String questionText;
    private Integer displayOrder;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CompanyPrepQuestionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private CompanyPrepProfile profile;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String questionText;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer displayOrder;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CompanyPrepQuestionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepQuestion.CompanyPrepQuestionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepQuestion.CompanyPrepQuestionBuilder profile(final CompanyPrepProfile profile) {
            this.profile = profile;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepQuestion.CompanyPrepQuestionBuilder questionText(final String questionText) {
            this.questionText = questionText;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepQuestion.CompanyPrepQuestionBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepQuestion build() {
            return new CompanyPrepQuestion(this.id, this.profile, this.questionText, this.displayOrder);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CompanyPrepQuestion.CompanyPrepQuestionBuilder(id=" + this.id + ", profile=" + this.profile + ", questionText=" + this.questionText + ", displayOrder=" + this.displayOrder + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CompanyPrepQuestion.CompanyPrepQuestionBuilder builder() {
        return new CompanyPrepQuestion.CompanyPrepQuestionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepProfile getProfile() {
        return this.profile;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQuestionText() {
        return this.questionText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProfile(final CompanyPrepProfile profile) {
        this.profile = profile;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuestionText(final String questionText) {
        this.questionText = questionText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayOrder(final Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CompanyPrepQuestion)) return false;
        final CompanyPrepQuestion other = (CompanyPrepQuestion) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$displayOrder = this.getDisplayOrder();
        final java.lang.Object other$displayOrder = other.getDisplayOrder();
        if (this$displayOrder == null ? other$displayOrder != null : !this$displayOrder.equals(other$displayOrder)) return false;
        final java.lang.Object this$profile = this.getProfile();
        final java.lang.Object other$profile = other.getProfile();
        if (this$profile == null ? other$profile != null : !this$profile.equals(other$profile)) return false;
        final java.lang.Object this$questionText = this.getQuestionText();
        final java.lang.Object other$questionText = other.getQuestionText();
        if (this$questionText == null ? other$questionText != null : !this$questionText.equals(other$questionText)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CompanyPrepQuestion;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $displayOrder = this.getDisplayOrder();
        result = result * PRIME + ($displayOrder == null ? 43 : $displayOrder.hashCode());
        final java.lang.Object $profile = this.getProfile();
        result = result * PRIME + ($profile == null ? 43 : $profile.hashCode());
        final java.lang.Object $questionText = this.getQuestionText();
        result = result * PRIME + ($questionText == null ? 43 : $questionText.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CompanyPrepQuestion(id=" + this.getId() + ", profile=" + this.getProfile() + ", questionText=" + this.getQuestionText() + ", displayOrder=" + this.getDisplayOrder() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepQuestion() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepQuestion(final Long id, final CompanyPrepProfile profile, final String questionText, final Integer displayOrder) {
        this.id = id;
        this.profile = profile;
        this.questionText = questionText;
        this.displayOrder = displayOrder;
    }
}
