// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "company_prep_recommendations")
public class CompanyPrepRecommendation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "profile_id", nullable = false)
    private CompanyPrepProfile profile;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "practice_problem_id", nullable = false)
    private PracticeProblem practiceProblem;
    private Integer displayOrder;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CompanyPrepRecommendationBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private CompanyPrepProfile profile;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PracticeProblem practiceProblem;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer displayOrder;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CompanyPrepRecommendationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepRecommendation.CompanyPrepRecommendationBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepRecommendation.CompanyPrepRecommendationBuilder profile(final CompanyPrepProfile profile) {
            this.profile = profile;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepRecommendation.CompanyPrepRecommendationBuilder practiceProblem(final PracticeProblem practiceProblem) {
            this.practiceProblem = practiceProblem;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepRecommendation.CompanyPrepRecommendationBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CompanyPrepRecommendation build() {
            return new CompanyPrepRecommendation(this.id, this.profile, this.practiceProblem, this.displayOrder);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CompanyPrepRecommendation.CompanyPrepRecommendationBuilder(id=" + this.id + ", profile=" + this.profile + ", practiceProblem=" + this.practiceProblem + ", displayOrder=" + this.displayOrder + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CompanyPrepRecommendation.CompanyPrepRecommendationBuilder builder() {
        return new CompanyPrepRecommendation.CompanyPrepRecommendationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepProfile getProfile() {
        return this.profile;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProblem getPracticeProblem() {
        return this.practiceProblem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProfile(final CompanyPrepProfile profile) {
        this.profile = profile;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPracticeProblem(final PracticeProblem practiceProblem) {
        this.practiceProblem = practiceProblem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayOrder(final Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CompanyPrepRecommendation)) return false;
        final CompanyPrepRecommendation other = (CompanyPrepRecommendation) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$displayOrder = this.getDisplayOrder();
        final java.lang.Object other$displayOrder = other.getDisplayOrder();
        if (this$displayOrder == null ? other$displayOrder != null : !this$displayOrder.equals(other$displayOrder)) return false;
        final java.lang.Object this$profile = this.getProfile();
        final java.lang.Object other$profile = other.getProfile();
        if (this$profile == null ? other$profile != null : !this$profile.equals(other$profile)) return false;
        final java.lang.Object this$practiceProblem = this.getPracticeProblem();
        final java.lang.Object other$practiceProblem = other.getPracticeProblem();
        if (this$practiceProblem == null ? other$practiceProblem != null : !this$practiceProblem.equals(other$practiceProblem)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CompanyPrepRecommendation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $displayOrder = this.getDisplayOrder();
        result = result * PRIME + ($displayOrder == null ? 43 : $displayOrder.hashCode());
        final java.lang.Object $profile = this.getProfile();
        result = result * PRIME + ($profile == null ? 43 : $profile.hashCode());
        final java.lang.Object $practiceProblem = this.getPracticeProblem();
        result = result * PRIME + ($practiceProblem == null ? 43 : $practiceProblem.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CompanyPrepRecommendation(id=" + this.getId() + ", profile=" + this.getProfile() + ", practiceProblem=" + this.getPracticeProblem() + ", displayOrder=" + this.getDisplayOrder() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepRecommendation() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CompanyPrepRecommendation(final Long id, final CompanyPrepProfile profile, final PracticeProblem practiceProblem, final Integer displayOrder) {
        this.id = id;
        this.profile = profile;
        this.practiceProblem = practiceProblem;
        this.displayOrder = displayOrder;
    }
}
