// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "interview_experiences")
public class InterviewExperience {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;
    private String userName; // For anonymous or quick-seeded experiences
    private String company;
    private String role;
    private String difficulty;
    private String date; // To match seeder
    @Enumerated(EnumType.STRING)
    private Outcome outcome;
    @Column(columnDefinition = "TEXT")
    private String description;
    private int rounds;
    private int upvotes;
    private int views;
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    public enum Outcome {
        Selected, Rejected, Pending;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class InterviewExperienceBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String userName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String company;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String role;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String difficulty;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String date;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Outcome outcome;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int rounds;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int upvotes;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int views;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        InterviewExperienceBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder company(final String company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder role(final String role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder difficulty(final String difficulty) {
            this.difficulty = difficulty;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder date(final String date) {
            this.date = date;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder outcome(final Outcome outcome) {
            this.outcome = outcome;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder rounds(final int rounds) {
            this.rounds = rounds;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder upvotes(final int upvotes) {
            this.upvotes = upvotes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder views(final int views) {
            this.views = views;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience.InterviewExperienceBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public InterviewExperience build() {
            return new InterviewExperience(this.id, this.user, this.userName, this.company, this.role, this.difficulty, this.date, this.outcome, this.description, this.rounds, this.upvotes, this.views, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "InterviewExperience.InterviewExperienceBuilder(id=" + this.id + ", user=" + this.user + ", userName=" + this.userName + ", company=" + this.company + ", role=" + this.role + ", difficulty=" + this.difficulty + ", date=" + this.date + ", outcome=" + this.outcome + ", description=" + this.description + ", rounds=" + this.rounds + ", upvotes=" + this.upvotes + ", views=" + this.views + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static InterviewExperience.InterviewExperienceBuilder builder() {
        return new InterviewExperience.InterviewExperienceBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUserName() {
        return this.userName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCompany() {
        return this.company;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDifficulty() {
        return this.difficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDate() {
        return this.date;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Outcome getOutcome() {
        return this.outcome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getRounds() {
        return this.rounds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getUpvotes() {
        return this.upvotes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getViews() {
        return this.views;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserName(final String userName) {
        this.userName = userName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompany(final String company) {
        this.company = company;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDifficulty(final String difficulty) {
        this.difficulty = difficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDate(final String date) {
        this.date = date;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOutcome(final Outcome outcome) {
        this.outcome = outcome;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRounds(final int rounds) {
        this.rounds = rounds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpvotes(final int upvotes) {
        this.upvotes = upvotes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setViews(final int views) {
        this.views = views;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof InterviewExperience)) return false;
        final InterviewExperience other = (InterviewExperience) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getRounds() != other.getRounds()) return false;
        if (this.getUpvotes() != other.getUpvotes()) return false;
        if (this.getViews() != other.getViews()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$company = this.getCompany();
        final java.lang.Object other$company = other.getCompany();
        if (this$company == null ? other$company != null : !this$company.equals(other$company)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$difficulty = this.getDifficulty();
        final java.lang.Object other$difficulty = other.getDifficulty();
        if (this$difficulty == null ? other$difficulty != null : !this$difficulty.equals(other$difficulty)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        final java.lang.Object this$outcome = this.getOutcome();
        final java.lang.Object other$outcome = other.getOutcome();
        if (this$outcome == null ? other$outcome != null : !this$outcome.equals(other$outcome)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof InterviewExperience;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getRounds();
        result = result * PRIME + this.getUpvotes();
        result = result * PRIME + this.getViews();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $company = this.getCompany();
        result = result * PRIME + ($company == null ? 43 : $company.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $difficulty = this.getDifficulty();
        result = result * PRIME + ($difficulty == null ? 43 : $difficulty.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        final java.lang.Object $outcome = this.getOutcome();
        result = result * PRIME + ($outcome == null ? 43 : $outcome.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "InterviewExperience(id=" + this.getId() + ", user=" + this.getUser() + ", userName=" + this.getUserName() + ", company=" + this.getCompany() + ", role=" + this.getRole() + ", difficulty=" + this.getDifficulty() + ", date=" + this.getDate() + ", outcome=" + this.getOutcome() + ", description=" + this.getDescription() + ", rounds=" + this.getRounds() + ", upvotes=" + this.getUpvotes() + ", views=" + this.getViews() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InterviewExperience() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InterviewExperience(final Long id, final User user, final String userName, final String company, final String role, final String difficulty, final String date, final Outcome outcome, final String description, final int rounds, final int upvotes, final int views, final LocalDateTime createdAt) {
        this.id = id;
        this.user = user;
        this.userName = userName;
        this.company = company;
        this.role = role;
        this.difficulty = difficulty;
        this.date = date;
        this.outcome = outcome;
        this.description = description;
        this.rounds = rounds;
        this.upvotes = upvotes;
        this.views = views;
        this.createdAt = createdAt;
    }
}
