// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "jobs")
public class Job {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String title;
    private String company;
    private String logoEmoji;
    private String location;
    private String salary;
    @Enumerated(EnumType.STRING)
    private JobType type;
    @ElementCollection
    @CollectionTable(name = "job_skills", joinColumns = @JoinColumn(name = "job_id"))
    @Column(name = "skill")
    private List<String> skills;
    private boolean isNew;
    private String applyLink;
    private LocalDateTime postedAt;

    @PrePersist
    protected void onCreate() {
        postedAt = LocalDateTime.now();
    }


    public enum JobType {
        FullTime, Internship, Remote;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class JobBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String title;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String company;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String logoEmoji;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String location;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String salary;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private JobType type;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<String> skills;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean isNew;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String applyLink;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime postedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        JobBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder company(final String company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder logoEmoji(final String logoEmoji) {
            this.logoEmoji = logoEmoji;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder location(final String location) {
            this.location = location;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder salary(final String salary) {
            this.salary = salary;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder type(final JobType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder skills(final List<String> skills) {
            this.skills = skills;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder isNew(final boolean isNew) {
            this.isNew = isNew;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder applyLink(final String applyLink) {
            this.applyLink = applyLink;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job.JobBuilder postedAt(final LocalDateTime postedAt) {
            this.postedAt = postedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Job build() {
            return new Job(this.id, this.title, this.company, this.logoEmoji, this.location, this.salary, this.type, this.skills, this.isNew, this.applyLink, this.postedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Job.JobBuilder(id=" + this.id + ", title=" + this.title + ", company=" + this.company + ", logoEmoji=" + this.logoEmoji + ", location=" + this.location + ", salary=" + this.salary + ", type=" + this.type + ", skills=" + this.skills + ", isNew=" + this.isNew + ", applyLink=" + this.applyLink + ", postedAt=" + this.postedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Job.JobBuilder builder() {
        return new Job.JobBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCompany() {
        return this.company;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogoEmoji() {
        return this.logoEmoji;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSalary() {
        return this.salary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public JobType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getSkills() {
        return this.skills;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isNew() {
        return this.isNew;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApplyLink() {
        return this.applyLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getPostedAt() {
        return this.postedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompany(final String company) {
        this.company = company;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogoEmoji(final String logoEmoji) {
        this.logoEmoji = logoEmoji;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLocation(final String location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSalary(final String salary) {
        this.salary = salary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final JobType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSkills(final List<String> skills) {
        this.skills = skills;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNew(final boolean isNew) {
        this.isNew = isNew;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApplyLink(final String applyLink) {
        this.applyLink = applyLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPostedAt(final LocalDateTime postedAt) {
        this.postedAt = postedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Job)) return false;
        final Job other = (Job) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isNew() != other.isNew()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$company = this.getCompany();
        final java.lang.Object other$company = other.getCompany();
        if (this$company == null ? other$company != null : !this$company.equals(other$company)) return false;
        final java.lang.Object this$logoEmoji = this.getLogoEmoji();
        final java.lang.Object other$logoEmoji = other.getLogoEmoji();
        if (this$logoEmoji == null ? other$logoEmoji != null : !this$logoEmoji.equals(other$logoEmoji)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        final java.lang.Object this$salary = this.getSalary();
        final java.lang.Object other$salary = other.getSalary();
        if (this$salary == null ? other$salary != null : !this$salary.equals(other$salary)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$skills = this.getSkills();
        final java.lang.Object other$skills = other.getSkills();
        if (this$skills == null ? other$skills != null : !this$skills.equals(other$skills)) return false;
        final java.lang.Object this$applyLink = this.getApplyLink();
        final java.lang.Object other$applyLink = other.getApplyLink();
        if (this$applyLink == null ? other$applyLink != null : !this$applyLink.equals(other$applyLink)) return false;
        final java.lang.Object this$postedAt = this.getPostedAt();
        final java.lang.Object other$postedAt = other.getPostedAt();
        if (this$postedAt == null ? other$postedAt != null : !this$postedAt.equals(other$postedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Job;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isNew() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $company = this.getCompany();
        result = result * PRIME + ($company == null ? 43 : $company.hashCode());
        final java.lang.Object $logoEmoji = this.getLogoEmoji();
        result = result * PRIME + ($logoEmoji == null ? 43 : $logoEmoji.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        final java.lang.Object $salary = this.getSalary();
        result = result * PRIME + ($salary == null ? 43 : $salary.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $skills = this.getSkills();
        result = result * PRIME + ($skills == null ? 43 : $skills.hashCode());
        final java.lang.Object $applyLink = this.getApplyLink();
        result = result * PRIME + ($applyLink == null ? 43 : $applyLink.hashCode());
        final java.lang.Object $postedAt = this.getPostedAt();
        result = result * PRIME + ($postedAt == null ? 43 : $postedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Job(id=" + this.getId() + ", title=" + this.getTitle() + ", company=" + this.getCompany() + ", logoEmoji=" + this.getLogoEmoji() + ", location=" + this.getLocation() + ", salary=" + this.getSalary() + ", type=" + this.getType() + ", skills=" + this.getSkills() + ", isNew=" + this.isNew() + ", applyLink=" + this.getApplyLink() + ", postedAt=" + this.getPostedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Job() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Job(final Long id, final String title, final String company, final String logoEmoji, final String location, final String salary, final JobType type, final List<String> skills, final boolean isNew, final String applyLink, final LocalDateTime postedAt) {
        this.id = id;
        this.title = title;
        this.company = company;
        this.logoEmoji = logoEmoji;
        this.location = location;
        this.salary = salary;
        this.type = type;
        this.skills = skills;
        this.isNew = isNew;
        this.applyLink = applyLink;
        this.postedAt = postedAt;
    }
}
