// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "mock_interviews")
public class MockInterview {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "interviewer_id")
    private User interviewer;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "interviewee_id")
    private User interviewee;
    private String topic; // Added for seeding
    private LocalDateTime scheduledTime; // Added for seeding
    private String scheduledAt;
    private String duration;
    private String role;
    private String roundType;
    private String focusArea;
    @Enumerated(EnumType.STRING)
    private InterviewStatus status;
    @Column(columnDefinition = "TEXT")
    private String feedback;
    private int rating; // 1-5
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    public enum InterviewStatus {
        Scheduled, Completed, Cancelled;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class MockInterviewBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User interviewer;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User interviewee;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String topic;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime scheduledTime;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String scheduledAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String duration;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String role;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String roundType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String focusArea;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private InterviewStatus status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String feedback;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int rating;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        MockInterviewBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder interviewer(final User interviewer) {
            this.interviewer = interviewer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder interviewee(final User interviewee) {
            this.interviewee = interviewee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder topic(final String topic) {
            this.topic = topic;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder scheduledTime(final LocalDateTime scheduledTime) {
            this.scheduledTime = scheduledTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder scheduledAt(final String scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder duration(final String duration) {
            this.duration = duration;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder focusArea(final String focusArea) {
            this.focusArea = focusArea;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder status(final InterviewStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder feedback(final String feedback) {
            this.feedback = feedback;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder rating(final int rating) {
            this.rating = rating;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview.MockInterviewBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MockInterview build() {
            return new MockInterview(this.id, this.interviewer, this.interviewee, this.topic, this.scheduledTime, this.scheduledAt, this.duration, this.role, this.roundType, this.focusArea, this.status, this.feedback, this.rating, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "MockInterview.MockInterviewBuilder(id=" + this.id + ", interviewer=" + this.interviewer + ", interviewee=" + this.interviewee + ", topic=" + this.topic + ", scheduledTime=" + this.scheduledTime + ", scheduledAt=" + this.scheduledAt + ", duration=" + this.duration + ", focusArea=" + this.focusArea + ", status=" + this.status + ", feedback=" + this.feedback + ", rating=" + this.rating + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static MockInterview.MockInterviewBuilder builder() {
        return new MockInterview.MockInterviewBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getInterviewer() {
        return this.interviewer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getInterviewee() {
        return this.interviewee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTopic() {
        return this.topic;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getScheduledTime() {
        return this.scheduledTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getScheduledAt() {
        return this.scheduledAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRoundType() {
        return this.roundType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFocusArea() {
        return this.focusArea;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public InterviewStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFeedback() {
        return this.feedback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterviewer(final User interviewer) {
        this.interviewer = interviewer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInterviewee(final User interviewee) {
        this.interviewee = interviewee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTopic(final String topic) {
        this.topic = topic;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScheduledTime(final LocalDateTime scheduledTime) {
        this.scheduledTime = scheduledTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScheduledAt(final String scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDuration(final String duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRoundType(final String roundType) {
        this.roundType = roundType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFocusArea(final String focusArea) {
        this.focusArea = focusArea;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final InterviewStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFeedback(final String feedback) {
        this.feedback = feedback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRating(final int rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MockInterview)) return false;
        final MockInterview other = (MockInterview) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getRating() != other.getRating()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$interviewer = this.getInterviewer();
        final java.lang.Object other$interviewer = other.getInterviewer();
        if (this$interviewer == null ? other$interviewer != null : !this$interviewer.equals(other$interviewer)) return false;
        final java.lang.Object this$interviewee = this.getInterviewee();
        final java.lang.Object other$interviewee = other.getInterviewee();
        if (this$interviewee == null ? other$interviewee != null : !this$interviewee.equals(other$interviewee)) return false;
        final java.lang.Object this$topic = this.getTopic();
        final java.lang.Object other$topic = other.getTopic();
        if (this$topic == null ? other$topic != null : !this$topic.equals(other$topic)) return false;
        final java.lang.Object this$scheduledTime = this.getScheduledTime();
        final java.lang.Object other$scheduledTime = other.getScheduledTime();
        if (this$scheduledTime == null ? other$scheduledTime != null : !this$scheduledTime.equals(other$scheduledTime)) return false;
        final java.lang.Object this$scheduledAt = this.getScheduledAt();
        final java.lang.Object other$scheduledAt = other.getScheduledAt();
        if (this$scheduledAt == null ? other$scheduledAt != null : !this$scheduledAt.equals(other$scheduledAt)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$focusArea = this.getFocusArea();
        final java.lang.Object other$focusArea = other.getFocusArea();
        if (this$focusArea == null ? other$focusArea != null : !this$focusArea.equals(other$focusArea)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$feedback = this.getFeedback();
        final java.lang.Object other$feedback = other.getFeedback();
        if (this$feedback == null ? other$feedback != null : !this$feedback.equals(other$feedback)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MockInterview;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getRating();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $interviewer = this.getInterviewer();
        result = result * PRIME + ($interviewer == null ? 43 : $interviewer.hashCode());
        final java.lang.Object $interviewee = this.getInterviewee();
        result = result * PRIME + ($interviewee == null ? 43 : $interviewee.hashCode());
        final java.lang.Object $topic = this.getTopic();
        result = result * PRIME + ($topic == null ? 43 : $topic.hashCode());
        final java.lang.Object $scheduledTime = this.getScheduledTime();
        result = result * PRIME + ($scheduledTime == null ? 43 : $scheduledTime.hashCode());
        final java.lang.Object $scheduledAt = this.getScheduledAt();
        result = result * PRIME + ($scheduledAt == null ? 43 : $scheduledAt.hashCode());
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $focusArea = this.getFocusArea();
        result = result * PRIME + ($focusArea == null ? 43 : $focusArea.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $feedback = this.getFeedback();
        result = result * PRIME + ($feedback == null ? 43 : $feedback.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "MockInterview(id=" + this.getId() + ", interviewer=" + this.getInterviewer() + ", interviewee=" + this.getInterviewee() + ", topic=" + this.getTopic() + ", scheduledTime=" + this.getScheduledTime() + ", scheduledAt=" + this.getScheduledAt() + ", duration=" + this.getDuration() + ", focusArea=" + this.getFocusArea() + ", status=" + this.getStatus() + ", feedback=" + this.getFeedback() + ", rating=" + this.getRating() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MockInterview() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MockInterview(final Long id, final User interviewer, final User interviewee, final String topic, final LocalDateTime scheduledTime, final String scheduledAt, final String duration, final String role, final String roundType, final String focusArea, final InterviewStatus status, final String feedback, final int rating, final LocalDateTime createdAt) {
        this.id = id;
        this.interviewer = interviewer;
        this.interviewee = interviewee;
        this.topic = topic;
        this.scheduledTime = scheduledTime;
        this.scheduledAt = scheduledAt;
        this.duration = duration;
        this.role = role;
        this.roundType = roundType;
        this.focusArea = focusArea;
        this.status = status;
        this.feedback = feedback;
        this.rating = rating;
        this.createdAt = createdAt;
    }
}
