// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "practice_progress", uniqueConstraints = {@UniqueConstraint(name = "uk_practice_progress_user_problem", columnNames = {"user_id", "problem_id"})})
public class PracticeProgress {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "problem_id", nullable = false)
    private PracticeProblem problem;
    @Column(nullable = false)
    private boolean completed;
    private LocalDateTime completedAt;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PracticeProgressBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PracticeProblem problem;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean completed;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime completedAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PracticeProgressBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder problem(final PracticeProblem problem) {
            this.problem = problem;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder completed(final boolean completed) {
            this.completed = completed;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder completedAt(final LocalDateTime completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress.PracticeProgressBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProgress build() {
            return new PracticeProgress(this.id, this.user, this.problem, this.completed, this.completedAt, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PracticeProgress.PracticeProgressBuilder(id=" + this.id + ", user=" + this.user + ", problem=" + this.problem + ", completed=" + this.completed + ", completedAt=" + this.completedAt + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static PracticeProgress.PracticeProgressBuilder builder() {
        return new PracticeProgress.PracticeProgressBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProblem getProblem() {
        return this.problem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isCompleted() {
        return this.completed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCompletedAt() {
        return this.completedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProblem(final PracticeProblem problem) {
        this.problem = problem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompleted(final boolean completed) {
        this.completed = completed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompletedAt(final LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PracticeProgress)) return false;
        final PracticeProgress other = (PracticeProgress) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isCompleted() != other.isCompleted()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$problem = this.getProblem();
        final java.lang.Object other$problem = other.getProblem();
        if (this$problem == null ? other$problem != null : !this$problem.equals(other$problem)) return false;
        final java.lang.Object this$completedAt = this.getCompletedAt();
        final java.lang.Object other$completedAt = other.getCompletedAt();
        if (this$completedAt == null ? other$completedAt != null : !this$completedAt.equals(other$completedAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PracticeProgress;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isCompleted() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $problem = this.getProblem();
        result = result * PRIME + ($problem == null ? 43 : $problem.hashCode());
        final java.lang.Object $completedAt = this.getCompletedAt();
        result = result * PRIME + ($completedAt == null ? 43 : $completedAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PracticeProgress(id=" + this.getId() + ", user=" + this.getUser() + ", problem=" + this.getProblem() + ", completed=" + this.isCompleted() + ", completedAt=" + this.getCompletedAt() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProgress() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProgress(final Long id, final User user, final PracticeProblem problem, final boolean completed, final LocalDateTime completedAt, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.user = user;
        this.problem = problem;
        this.completed = completed;
        this.completedAt = completedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
