// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "practice_problems")
public class PracticeProblem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String title;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "topic_id", nullable = false)
    private PracticeTopic topic;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Difficulty difficulty;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Platform platform;
    @Column(nullable = false, length = 1024)
    private String problemUrl;
    @Column(columnDefinition = "TEXT")
    private String summary;
    private Integer displayOrder;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    public enum Difficulty {
        Easy, Medium, Hard;
    }


    public enum Platform {
        LeetCode, GeeksForGeeks;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PracticeProblemBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String title;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PracticeTopic topic;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Difficulty difficulty;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Platform platform;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String problemUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String summary;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer displayOrder;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PracticeProblemBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder topic(final PracticeTopic topic) {
            this.topic = topic;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder difficulty(final Difficulty difficulty) {
            this.difficulty = difficulty;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder platform(final Platform platform) {
            this.platform = platform;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder problemUrl(final String problemUrl) {
            this.problemUrl = problemUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder summary(final String summary) {
            this.summary = summary;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem.PracticeProblemBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeProblem build() {
            return new PracticeProblem(this.id, this.title, this.topic, this.difficulty, this.platform, this.problemUrl, this.summary, this.displayOrder, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PracticeProblem.PracticeProblemBuilder(id=" + this.id + ", title=" + this.title + ", topic=" + this.topic + ", difficulty=" + this.difficulty + ", platform=" + this.platform + ", problemUrl=" + this.problemUrl + ", summary=" + this.summary + ", displayOrder=" + this.displayOrder + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static PracticeProblem.PracticeProblemBuilder builder() {
        return new PracticeProblem.PracticeProblemBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeTopic getTopic() {
        return this.topic;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Difficulty getDifficulty() {
        return this.difficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Platform getPlatform() {
        return this.platform;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProblemUrl() {
        return this.problemUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSummary() {
        return this.summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTopic(final PracticeTopic topic) {
        this.topic = topic;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDifficulty(final Difficulty difficulty) {
        this.difficulty = difficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlatform(final Platform platform) {
        this.platform = platform;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProblemUrl(final String problemUrl) {
        this.problemUrl = problemUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSummary(final String summary) {
        this.summary = summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayOrder(final Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PracticeProblem)) return false;
        final PracticeProblem other = (PracticeProblem) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$displayOrder = this.getDisplayOrder();
        final java.lang.Object other$displayOrder = other.getDisplayOrder();
        if (this$displayOrder == null ? other$displayOrder != null : !this$displayOrder.equals(other$displayOrder)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$topic = this.getTopic();
        final java.lang.Object other$topic = other.getTopic();
        if (this$topic == null ? other$topic != null : !this$topic.equals(other$topic)) return false;
        final java.lang.Object this$difficulty = this.getDifficulty();
        final java.lang.Object other$difficulty = other.getDifficulty();
        if (this$difficulty == null ? other$difficulty != null : !this$difficulty.equals(other$difficulty)) return false;
        final java.lang.Object this$platform = this.getPlatform();
        final java.lang.Object other$platform = other.getPlatform();
        if (this$platform == null ? other$platform != null : !this$platform.equals(other$platform)) return false;
        final java.lang.Object this$problemUrl = this.getProblemUrl();
        final java.lang.Object other$problemUrl = other.getProblemUrl();
        if (this$problemUrl == null ? other$problemUrl != null : !this$problemUrl.equals(other$problemUrl)) return false;
        final java.lang.Object this$summary = this.getSummary();
        final java.lang.Object other$summary = other.getSummary();
        if (this$summary == null ? other$summary != null : !this$summary.equals(other$summary)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PracticeProblem;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $displayOrder = this.getDisplayOrder();
        result = result * PRIME + ($displayOrder == null ? 43 : $displayOrder.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $topic = this.getTopic();
        result = result * PRIME + ($topic == null ? 43 : $topic.hashCode());
        final java.lang.Object $difficulty = this.getDifficulty();
        result = result * PRIME + ($difficulty == null ? 43 : $difficulty.hashCode());
        final java.lang.Object $platform = this.getPlatform();
        result = result * PRIME + ($platform == null ? 43 : $platform.hashCode());
        final java.lang.Object $problemUrl = this.getProblemUrl();
        result = result * PRIME + ($problemUrl == null ? 43 : $problemUrl.hashCode());
        final java.lang.Object $summary = this.getSummary();
        result = result * PRIME + ($summary == null ? 43 : $summary.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PracticeProblem(id=" + this.getId() + ", title=" + this.getTitle() + ", topic=" + this.getTopic() + ", difficulty=" + this.getDifficulty() + ", platform=" + this.getPlatform() + ", problemUrl=" + this.getProblemUrl() + ", summary=" + this.getSummary() + ", displayOrder=" + this.getDisplayOrder() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProblem() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProblem(final Long id, final String title, final PracticeTopic topic, final Difficulty difficulty, final Platform platform, final String problemUrl, final String summary, final Integer displayOrder, final LocalDateTime createdAt) {
        this.id = id;
        this.title = title;
        this.topic = topic;
        this.difficulty = difficulty;
        this.platform = platform;
        this.problemUrl = problemUrl;
        this.summary = summary;
        this.displayOrder = displayOrder;
        this.createdAt = createdAt;
    }
}
