// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "practice_topics")
public class PracticeTopic {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true)
    private String name;
    @Column(nullable = false, unique = true)
    private String slug;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String iconName;
    private String accentColor;
    private Integer displayOrder;
    @OneToMany(mappedBy = "topic")
    private List<PracticeProblem> problems;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static List<PracticeProblem> $default$problems() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PracticeTopicBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String slug;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String iconName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String accentColor;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer displayOrder;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean problems$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<PracticeProblem> problems$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PracticeTopicBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder slug(final String slug) {
            this.slug = slug;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder iconName(final String iconName) {
            this.iconName = iconName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder accentColor(final String accentColor) {
            this.accentColor = accentColor;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder problems(final List<PracticeProblem> problems) {
            this.problems$value = problems;
            problems$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic.PracticeTopicBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PracticeTopic build() {
            List<PracticeProblem> problems$value = this.problems$value;
            if (!this.problems$set) problems$value = PracticeTopic.$default$problems();
            return new PracticeTopic(this.id, this.name, this.slug, this.description, this.iconName, this.accentColor, this.displayOrder, problems$value, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PracticeTopic.PracticeTopicBuilder(id=" + this.id + ", name=" + this.name + ", slug=" + this.slug + ", description=" + this.description + ", iconName=" + this.iconName + ", accentColor=" + this.accentColor + ", displayOrder=" + this.displayOrder + ", problems$value=" + this.problems$value + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static PracticeTopic.PracticeTopicBuilder builder() {
        return new PracticeTopic.PracticeTopicBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSlug() {
        return this.slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getIconName() {
        return this.iconName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAccentColor() {
        return this.accentColor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<PracticeProblem> getProblems() {
        return this.problems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSlug(final String slug) {
        this.slug = slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIconName(final String iconName) {
        this.iconName = iconName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAccentColor(final String accentColor) {
        this.accentColor = accentColor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayOrder(final Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProblems(final List<PracticeProblem> problems) {
        this.problems = problems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PracticeTopic)) return false;
        final PracticeTopic other = (PracticeTopic) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$displayOrder = this.getDisplayOrder();
        final java.lang.Object other$displayOrder = other.getDisplayOrder();
        if (this$displayOrder == null ? other$displayOrder != null : !this$displayOrder.equals(other$displayOrder)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$slug = this.getSlug();
        final java.lang.Object other$slug = other.getSlug();
        if (this$slug == null ? other$slug != null : !this$slug.equals(other$slug)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$iconName = this.getIconName();
        final java.lang.Object other$iconName = other.getIconName();
        if (this$iconName == null ? other$iconName != null : !this$iconName.equals(other$iconName)) return false;
        final java.lang.Object this$accentColor = this.getAccentColor();
        final java.lang.Object other$accentColor = other.getAccentColor();
        if (this$accentColor == null ? other$accentColor != null : !this$accentColor.equals(other$accentColor)) return false;
        final java.lang.Object this$problems = this.getProblems();
        final java.lang.Object other$problems = other.getProblems();
        if (this$problems == null ? other$problems != null : !this$problems.equals(other$problems)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PracticeTopic;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $displayOrder = this.getDisplayOrder();
        result = result * PRIME + ($displayOrder == null ? 43 : $displayOrder.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $slug = this.getSlug();
        result = result * PRIME + ($slug == null ? 43 : $slug.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $iconName = this.getIconName();
        result = result * PRIME + ($iconName == null ? 43 : $iconName.hashCode());
        final java.lang.Object $accentColor = this.getAccentColor();
        result = result * PRIME + ($accentColor == null ? 43 : $accentColor.hashCode());
        final java.lang.Object $problems = this.getProblems();
        result = result * PRIME + ($problems == null ? 43 : $problems.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PracticeTopic(id=" + this.getId() + ", name=" + this.getName() + ", slug=" + this.getSlug() + ", description=" + this.getDescription() + ", iconName=" + this.getIconName() + ", accentColor=" + this.getAccentColor() + ", displayOrder=" + this.getDisplayOrder() + ", problems=" + this.getProblems() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeTopic() {
        this.problems = PracticeTopic.$default$problems();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeTopic(final Long id, final String name, final String slug, final String description, final String iconName, final String accentColor, final Integer displayOrder, final List<PracticeProblem> problems, final LocalDateTime createdAt) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.description = description;
        this.iconName = iconName;
        this.accentColor = accentColor;
        this.displayOrder = displayOrder;
        this.problems = problems;
        this.createdAt = createdAt;
    }
}
