// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "problems")
public class Problem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String title;
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private Difficulty difficulty;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String acceptanceRate;
    private int frequency;
    @ElementCollection
    @CollectionTable(name = "problem_topics", joinColumns = @JoinColumn(name = "problem_id"))
    @Column(name = "topic")
    private List<String> topics;
    @ElementCollection
    @CollectionTable(name = "problem_companies", joinColumns = @JoinColumn(name = "problem_id"))
    @Column(name = "company")
    private List<String> companies;
    @Column(columnDefinition = "TEXT")
    private String constraints;
    @Column(columnDefinition = "TEXT")
    private String hints;
    @Column(columnDefinition = "TEXT")
    private String editorial;
    @Column(columnDefinition = "TEXT")
    private String starterCodeJava;
    @Column(columnDefinition = "TEXT")
    private String starterCodePython;
    @Column(columnDefinition = "TEXT")
    private String starterCodeCpp;
    @Column(columnDefinition = "TEXT")
    private String starterCodeJs;
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    public enum Difficulty {
        Easy, Medium, Hard;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProblemBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String title;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Difficulty difficulty;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String acceptanceRate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int frequency;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<String> topics;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<String> companies;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String constraints;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String hints;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String editorial;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String starterCodeJava;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String starterCodePython;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String starterCodeCpp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String starterCodeJs;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProblemBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder difficulty(final Difficulty difficulty) {
            this.difficulty = difficulty;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder acceptanceRate(final String acceptanceRate) {
            this.acceptanceRate = acceptanceRate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder frequency(final int frequency) {
            this.frequency = frequency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder topics(final List<String> topics) {
            this.topics = topics;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder companies(final List<String> companies) {
            this.companies = companies;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder constraints(final String constraints) {
            this.constraints = constraints;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder hints(final String hints) {
            this.hints = hints;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder editorial(final String editorial) {
            this.editorial = editorial;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder starterCodeJava(final String starterCodeJava) {
            this.starterCodeJava = starterCodeJava;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder starterCodePython(final String starterCodePython) {
            this.starterCodePython = starterCodePython;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder starterCodeCpp(final String starterCodeCpp) {
            this.starterCodeCpp = starterCodeCpp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder starterCodeJs(final String starterCodeJs) {
            this.starterCodeJs = starterCodeJs;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem.ProblemBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Problem build() {
            return new Problem(this.id, this.title, this.difficulty, this.description, this.acceptanceRate, this.frequency, this.topics, this.companies, this.constraints, this.hints, this.editorial, this.starterCodeJava, this.starterCodePython, this.starterCodeCpp, this.starterCodeJs, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Problem.ProblemBuilder(id=" + this.id + ", title=" + this.title + ", difficulty=" + this.difficulty + ", description=" + this.description + ", acceptanceRate=" + this.acceptanceRate + ", frequency=" + this.frequency + ", topics=" + this.topics + ", companies=" + this.companies + ", constraints=" + this.constraints + ", hints=" + this.hints + ", editorial=" + this.editorial + ", starterCodeJava=" + this.starterCodeJava + ", starterCodePython=" + this.starterCodePython + ", starterCodeCpp=" + this.starterCodeCpp + ", starterCodeJs=" + this.starterCodeJs + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Problem.ProblemBuilder builder() {
        return new Problem.ProblemBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Difficulty getDifficulty() {
        return this.difficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAcceptanceRate() {
        return this.acceptanceRate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getFrequency() {
        return this.frequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getTopics() {
        return this.topics;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getCompanies() {
        return this.companies;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getConstraints() {
        return this.constraints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHints() {
        return this.hints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEditorial() {
        return this.editorial;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStarterCodeJava() {
        return this.starterCodeJava;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStarterCodePython() {
        return this.starterCodePython;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStarterCodeCpp() {
        return this.starterCodeCpp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStarterCodeJs() {
        return this.starterCodeJs;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDifficulty(final Difficulty difficulty) {
        this.difficulty = difficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAcceptanceRate(final String acceptanceRate) {
        this.acceptanceRate = acceptanceRate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFrequency(final int frequency) {
        this.frequency = frequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTopics(final List<String> topics) {
        this.topics = topics;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompanies(final List<String> companies) {
        this.companies = companies;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setConstraints(final String constraints) {
        this.constraints = constraints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHints(final String hints) {
        this.hints = hints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEditorial(final String editorial) {
        this.editorial = editorial;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStarterCodeJava(final String starterCodeJava) {
        this.starterCodeJava = starterCodeJava;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStarterCodePython(final String starterCodePython) {
        this.starterCodePython = starterCodePython;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStarterCodeCpp(final String starterCodeCpp) {
        this.starterCodeCpp = starterCodeCpp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStarterCodeJs(final String starterCodeJs) {
        this.starterCodeJs = starterCodeJs;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Problem)) return false;
        final Problem other = (Problem) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getFrequency() != other.getFrequency()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$difficulty = this.getDifficulty();
        final java.lang.Object other$difficulty = other.getDifficulty();
        if (this$difficulty == null ? other$difficulty != null : !this$difficulty.equals(other$difficulty)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$acceptanceRate = this.getAcceptanceRate();
        final java.lang.Object other$acceptanceRate = other.getAcceptanceRate();
        if (this$acceptanceRate == null ? other$acceptanceRate != null : !this$acceptanceRate.equals(other$acceptanceRate)) return false;
        final java.lang.Object this$topics = this.getTopics();
        final java.lang.Object other$topics = other.getTopics();
        if (this$topics == null ? other$topics != null : !this$topics.equals(other$topics)) return false;
        final java.lang.Object this$companies = this.getCompanies();
        final java.lang.Object other$companies = other.getCompanies();
        if (this$companies == null ? other$companies != null : !this$companies.equals(other$companies)) return false;
        final java.lang.Object this$constraints = this.getConstraints();
        final java.lang.Object other$constraints = other.getConstraints();
        if (this$constraints == null ? other$constraints != null : !this$constraints.equals(other$constraints)) return false;
        final java.lang.Object this$hints = this.getHints();
        final java.lang.Object other$hints = other.getHints();
        if (this$hints == null ? other$hints != null : !this$hints.equals(other$hints)) return false;
        final java.lang.Object this$editorial = this.getEditorial();
        final java.lang.Object other$editorial = other.getEditorial();
        if (this$editorial == null ? other$editorial != null : !this$editorial.equals(other$editorial)) return false;
        final java.lang.Object this$starterCodeJava = this.getStarterCodeJava();
        final java.lang.Object other$starterCodeJava = other.getStarterCodeJava();
        if (this$starterCodeJava == null ? other$starterCodeJava != null : !this$starterCodeJava.equals(other$starterCodeJava)) return false;
        final java.lang.Object this$starterCodePython = this.getStarterCodePython();
        final java.lang.Object other$starterCodePython = other.getStarterCodePython();
        if (this$starterCodePython == null ? other$starterCodePython != null : !this$starterCodePython.equals(other$starterCodePython)) return false;
        final java.lang.Object this$starterCodeCpp = this.getStarterCodeCpp();
        final java.lang.Object other$starterCodeCpp = other.getStarterCodeCpp();
        if (this$starterCodeCpp == null ? other$starterCodeCpp != null : !this$starterCodeCpp.equals(other$starterCodeCpp)) return false;
        final java.lang.Object this$starterCodeJs = this.getStarterCodeJs();
        final java.lang.Object other$starterCodeJs = other.getStarterCodeJs();
        if (this$starterCodeJs == null ? other$starterCodeJs != null : !this$starterCodeJs.equals(other$starterCodeJs)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Problem;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getFrequency();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $difficulty = this.getDifficulty();
        result = result * PRIME + ($difficulty == null ? 43 : $difficulty.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $acceptanceRate = this.getAcceptanceRate();
        result = result * PRIME + ($acceptanceRate == null ? 43 : $acceptanceRate.hashCode());
        final java.lang.Object $topics = this.getTopics();
        result = result * PRIME + ($topics == null ? 43 : $topics.hashCode());
        final java.lang.Object $companies = this.getCompanies();
        result = result * PRIME + ($companies == null ? 43 : $companies.hashCode());
        final java.lang.Object $constraints = this.getConstraints();
        result = result * PRIME + ($constraints == null ? 43 : $constraints.hashCode());
        final java.lang.Object $hints = this.getHints();
        result = result * PRIME + ($hints == null ? 43 : $hints.hashCode());
        final java.lang.Object $editorial = this.getEditorial();
        result = result * PRIME + ($editorial == null ? 43 : $editorial.hashCode());
        final java.lang.Object $starterCodeJava = this.getStarterCodeJava();
        result = result * PRIME + ($starterCodeJava == null ? 43 : $starterCodeJava.hashCode());
        final java.lang.Object $starterCodePython = this.getStarterCodePython();
        result = result * PRIME + ($starterCodePython == null ? 43 : $starterCodePython.hashCode());
        final java.lang.Object $starterCodeCpp = this.getStarterCodeCpp();
        result = result * PRIME + ($starterCodeCpp == null ? 43 : $starterCodeCpp.hashCode());
        final java.lang.Object $starterCodeJs = this.getStarterCodeJs();
        result = result * PRIME + ($starterCodeJs == null ? 43 : $starterCodeJs.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Problem(id=" + this.getId() + ", title=" + this.getTitle() + ", difficulty=" + this.getDifficulty() + ", description=" + this.getDescription() + ", acceptanceRate=" + this.getAcceptanceRate() + ", frequency=" + this.getFrequency() + ", topics=" + this.getTopics() + ", companies=" + this.getCompanies() + ", constraints=" + this.getConstraints() + ", hints=" + this.getHints() + ", editorial=" + this.getEditorial() + ", starterCodeJava=" + this.getStarterCodeJava() + ", starterCodePython=" + this.getStarterCodePython() + ", starterCodeCpp=" + this.getStarterCodeCpp() + ", starterCodeJs=" + this.getStarterCodeJs() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Problem() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Problem(final Long id, final String title, final Difficulty difficulty, final String description, final String acceptanceRate, final int frequency, final List<String> topics, final List<String> companies, final String constraints, final String hints, final String editorial, final String starterCodeJava, final String starterCodePython, final String starterCodeCpp, final String starterCodeJs, final LocalDateTime createdAt) {
        this.id = id;
        this.title = title;
        this.difficulty = difficulty;
        this.description = description;
        this.acceptanceRate = acceptanceRate;
        this.frequency = frequency;
        this.topics = topics;
        this.companies = companies;
        this.constraints = constraints;
        this.hints = hints;
        this.editorial = editorial;
        this.starterCodeJava = starterCodeJava;
        this.starterCodePython = starterCodePython;
        this.starterCodeCpp = starterCodeCpp;
        this.starterCodeJs = starterCodeJs;
        this.createdAt = createdAt;
    }
}
