// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "submissions")
public class Submission {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "problem_id", nullable = false)
    private Problem problem;
    @Enumerated(EnumType.STRING)
    private Status status;
    private String language;
    private String runtime;
    private String memory;
    @Column(columnDefinition = "TEXT")
    private String code;
    private LocalDateTime submittedAt;

    @PrePersist
    protected void onCreate() {
        submittedAt = LocalDateTime.now();
    }


    public enum Status {
        Accepted, WrongAnswer, TimeLimitExceeded, RuntimeError, CompileError;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class SubmissionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Problem problem;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Status status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String language;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String runtime;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String memory;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String code;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime submittedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        SubmissionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder problem(final Problem problem) {
            this.problem = problem;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder status(final Status status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder language(final String language) {
            this.language = language;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder runtime(final String runtime) {
            this.runtime = runtime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder memory(final String memory) {
            this.memory = memory;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder code(final String code) {
            this.code = code;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission.SubmissionBuilder submittedAt(final LocalDateTime submittedAt) {
            this.submittedAt = submittedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Submission build() {
            return new Submission(this.id, this.user, this.problem, this.status, this.language, this.runtime, this.memory, this.code, this.submittedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Submission.SubmissionBuilder(id=" + this.id + ", user=" + this.user + ", problem=" + this.problem + ", status=" + this.status + ", language=" + this.language + ", runtime=" + this.runtime + ", memory=" + this.memory + ", code=" + this.code + ", submittedAt=" + this.submittedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Submission.SubmissionBuilder builder() {
        return new Submission.SubmissionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Problem getProblem() {
        return this.problem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Status getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLanguage() {
        return this.language;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRuntime() {
        return this.runtime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMemory() {
        return this.memory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getSubmittedAt() {
        return this.submittedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProblem(final Problem problem) {
        this.problem = problem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Status status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLanguage(final String language) {
        this.language = language;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRuntime(final String runtime) {
        this.runtime = runtime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMemory(final String memory) {
        this.memory = memory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubmittedAt(final LocalDateTime submittedAt) {
        this.submittedAt = submittedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Submission)) return false;
        final Submission other = (Submission) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$problem = this.getProblem();
        final java.lang.Object other$problem = other.getProblem();
        if (this$problem == null ? other$problem != null : !this$problem.equals(other$problem)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$language = this.getLanguage();
        final java.lang.Object other$language = other.getLanguage();
        if (this$language == null ? other$language != null : !this$language.equals(other$language)) return false;
        final java.lang.Object this$runtime = this.getRuntime();
        final java.lang.Object other$runtime = other.getRuntime();
        if (this$runtime == null ? other$runtime != null : !this$runtime.equals(other$runtime)) return false;
        final java.lang.Object this$memory = this.getMemory();
        final java.lang.Object other$memory = other.getMemory();
        if (this$memory == null ? other$memory != null : !this$memory.equals(other$memory)) return false;
        final java.lang.Object this$code = this.getCode();
        final java.lang.Object other$code = other.getCode();
        if (this$code == null ? other$code != null : !this$code.equals(other$code)) return false;
        final java.lang.Object this$submittedAt = this.getSubmittedAt();
        final java.lang.Object other$submittedAt = other.getSubmittedAt();
        if (this$submittedAt == null ? other$submittedAt != null : !this$submittedAt.equals(other$submittedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Submission;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $problem = this.getProblem();
        result = result * PRIME + ($problem == null ? 43 : $problem.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $language = this.getLanguage();
        result = result * PRIME + ($language == null ? 43 : $language.hashCode());
        final java.lang.Object $runtime = this.getRuntime();
        result = result * PRIME + ($runtime == null ? 43 : $runtime.hashCode());
        final java.lang.Object $memory = this.getMemory();
        result = result * PRIME + ($memory == null ? 43 : $memory.hashCode());
        final java.lang.Object $code = this.getCode();
        result = result * PRIME + ($code == null ? 43 : $code.hashCode());
        final java.lang.Object $submittedAt = this.getSubmittedAt();
        result = result * PRIME + ($submittedAt == null ? 43 : $submittedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Submission(id=" + this.getId() + ", user=" + this.getUser() + ", problem=" + this.getProblem() + ", status=" + this.getStatus() + ", language=" + this.getLanguage() + ", runtime=" + this.getRuntime() + ", memory=" + this.getMemory() + ", code=" + this.getCode() + ", submittedAt=" + this.getSubmittedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Submission() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Submission(final Long id, final User user, final Problem problem, final Status status, final String language, final String runtime, final String memory, final String code, final LocalDateTime submittedAt) {
        this.id = id;
        this.user = user;
        this.problem = problem;
        this.status = status;
        this.language = language;
        this.runtime = runtime;
        this.memory = memory;
        this.code = code;
        this.submittedAt = submittedAt;
    }
}
