// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String firstName;
    @Column(nullable = false)
    private String lastName;
    @Column(nullable = false, unique = true)
    private String email;
    @Column(nullable = false)
    private String password;
    private String college;
    private String branch;
    private String gradYear;
    private String primaryGoal;
    // Stats
    private int problemsSolved;
    private int currentStreak;
    private int bestStreak;
    private int xp;
    private int level;
    private String league;
    private int globalRank;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime lastLogin;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static int $default$problemsSolved() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static int $default$currentStreak() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static int $default$bestStreak() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static int $default$xp() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static int $default$level() {
        return 1;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$league() {
        return "Bronze";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class UserBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String firstName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String lastName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String password;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String college;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String branch;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String gradYear;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String primaryGoal;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean problemsSolved$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int problemsSolved$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean currentStreak$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int currentStreak$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean bestStreak$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int bestStreak$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean xp$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int xp$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean level$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int level$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean league$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String league$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int globalRank;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime lastLogin;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder firstName(final String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder lastName(final String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder password(final String password) {
            this.password = password;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder college(final String college) {
            this.college = college;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder branch(final String branch) {
            this.branch = branch;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder gradYear(final String gradYear) {
            this.gradYear = gradYear;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder primaryGoal(final String primaryGoal) {
            this.primaryGoal = primaryGoal;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder problemsSolved(final int problemsSolved) {
            this.problemsSolved$value = problemsSolved;
            problemsSolved$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder currentStreak(final int currentStreak) {
            this.currentStreak$value = currentStreak;
            currentStreak$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder bestStreak(final int bestStreak) {
            this.bestStreak$value = bestStreak;
            bestStreak$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder xp(final int xp) {
            this.xp$value = xp;
            xp$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder level(final int level) {
            this.level$value = level;
            level$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder league(final String league) {
            this.league$value = league;
            league$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder globalRank(final int globalRank) {
            this.globalRank = globalRank;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder lastLogin(final LocalDateTime lastLogin) {
            this.lastLogin = lastLogin;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User build() {
            int problemsSolved$value = this.problemsSolved$value;
            if (!this.problemsSolved$set) problemsSolved$value = User.$default$problemsSolved();
            int currentStreak$value = this.currentStreak$value;
            if (!this.currentStreak$set) currentStreak$value = User.$default$currentStreak();
            int bestStreak$value = this.bestStreak$value;
            if (!this.bestStreak$set) bestStreak$value = User.$default$bestStreak();
            int xp$value = this.xp$value;
            if (!this.xp$set) xp$value = User.$default$xp();
            int level$value = this.level$value;
            if (!this.level$set) level$value = User.$default$level();
            String league$value = this.league$value;
            if (!this.league$set) league$value = User.$default$league();
            return new User(this.id, this.firstName, this.lastName, this.email, this.password, this.college, this.branch, this.gradYear, this.primaryGoal, problemsSolved$value, currentStreak$value, bestStreak$value, xp$value, level$value, league$value, this.globalRank, this.createdAt, this.lastLogin);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", firstName=" + this.firstName + ", lastName=" + this.lastName + ", email=" + this.email + ", password=" + this.password + ", college=" + this.college + ", branch=" + this.branch + ", gradYear=" + this.gradYear + ", primaryGoal=" + this.primaryGoal + ", problemsSolved$value=" + this.problemsSolved$value + ", currentStreak$value=" + this.currentStreak$value + ", bestStreak$value=" + this.bestStreak$value + ", xp$value=" + this.xp$value + ", level$value=" + this.level$value + ", league$value=" + this.league$value + ", globalRank=" + this.globalRank + ", createdAt=" + this.createdAt + ", lastLogin=" + this.lastLogin + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCollege() {
        return this.college;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBranch() {
        return this.branch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGradYear() {
        return this.gradYear;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrimaryGoal() {
        return this.primaryGoal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getProblemsSolved() {
        return this.problemsSolved;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCurrentStreak() {
        return this.currentStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getBestStreak() {
        return this.bestStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getXp() {
        return this.xp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getLevel() {
        return this.level;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLeague() {
        return this.league;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getGlobalRank() {
        return this.globalRank;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getLastLogin() {
        return this.lastLogin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCollege(final String college) {
        this.college = college;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBranch(final String branch) {
        this.branch = branch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGradYear(final String gradYear) {
        this.gradYear = gradYear;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrimaryGoal(final String primaryGoal) {
        this.primaryGoal = primaryGoal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProblemsSolved(final int problemsSolved) {
        this.problemsSolved = problemsSolved;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentStreak(final int currentStreak) {
        this.currentStreak = currentStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBestStreak(final int bestStreak) {
        this.bestStreak = bestStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setXp(final int xp) {
        this.xp = xp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLevel(final int level) {
        this.level = level;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLeague(final String league) {
        this.league = league;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGlobalRank(final int globalRank) {
        this.globalRank = globalRank;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastLogin(final LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getProblemsSolved() != other.getProblemsSolved()) return false;
        if (this.getCurrentStreak() != other.getCurrentStreak()) return false;
        if (this.getBestStreak() != other.getBestStreak()) return false;
        if (this.getXp() != other.getXp()) return false;
        if (this.getLevel() != other.getLevel()) return false;
        if (this.getGlobalRank() != other.getGlobalRank()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$college = this.getCollege();
        final java.lang.Object other$college = other.getCollege();
        if (this$college == null ? other$college != null : !this$college.equals(other$college)) return false;
        final java.lang.Object this$branch = this.getBranch();
        final java.lang.Object other$branch = other.getBranch();
        if (this$branch == null ? other$branch != null : !this$branch.equals(other$branch)) return false;
        final java.lang.Object this$gradYear = this.getGradYear();
        final java.lang.Object other$gradYear = other.getGradYear();
        if (this$gradYear == null ? other$gradYear != null : !this$gradYear.equals(other$gradYear)) return false;
        final java.lang.Object this$primaryGoal = this.getPrimaryGoal();
        final java.lang.Object other$primaryGoal = other.getPrimaryGoal();
        if (this$primaryGoal == null ? other$primaryGoal != null : !this$primaryGoal.equals(other$primaryGoal)) return false;
        final java.lang.Object this$league = this.getLeague();
        final java.lang.Object other$league = other.getLeague();
        if (this$league == null ? other$league != null : !this$league.equals(other$league)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$lastLogin = this.getLastLogin();
        final java.lang.Object other$lastLogin = other.getLastLogin();
        if (this$lastLogin == null ? other$lastLogin != null : !this$lastLogin.equals(other$lastLogin)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getProblemsSolved();
        result = result * PRIME + this.getCurrentStreak();
        result = result * PRIME + this.getBestStreak();
        result = result * PRIME + this.getXp();
        result = result * PRIME + this.getLevel();
        result = result * PRIME + this.getGlobalRank();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $college = this.getCollege();
        result = result * PRIME + ($college == null ? 43 : $college.hashCode());
        final java.lang.Object $branch = this.getBranch();
        result = result * PRIME + ($branch == null ? 43 : $branch.hashCode());
        final java.lang.Object $gradYear = this.getGradYear();
        result = result * PRIME + ($gradYear == null ? 43 : $gradYear.hashCode());
        final java.lang.Object $primaryGoal = this.getPrimaryGoal();
        result = result * PRIME + ($primaryGoal == null ? 43 : $primaryGoal.hashCode());
        final java.lang.Object $league = this.getLeague();
        result = result * PRIME + ($league == null ? 43 : $league.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $lastLogin = this.getLastLogin();
        result = result * PRIME + ($lastLogin == null ? 43 : $lastLogin.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "User(id=" + this.getId() + ", firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", college=" + this.getCollege() + ", branch=" + this.getBranch() + ", gradYear=" + this.getGradYear() + ", primaryGoal=" + this.getPrimaryGoal() + ", problemsSolved=" + this.getProblemsSolved() + ", currentStreak=" + this.getCurrentStreak() + ", bestStreak=" + this.getBestStreak() + ", xp=" + this.getXp() + ", level=" + this.getLevel() + ", league=" + this.getLeague() + ", globalRank=" + this.getGlobalRank() + ", createdAt=" + this.getCreatedAt() + ", lastLogin=" + this.getLastLogin() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User() {
        this.problemsSolved = User.$default$problemsSolved();
        this.currentStreak = User.$default$currentStreak();
        this.bestStreak = User.$default$bestStreak();
        this.xp = User.$default$xp();
        this.level = User.$default$level();
        this.league = User.$default$league();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User(final Long id, final String firstName, final String lastName, final String email, final String password, final String college, final String branch, final String gradYear, final String primaryGoal, final int problemsSolved, final int currentStreak, final int bestStreak, final int xp, final int level, final String league, final int globalRank, final LocalDateTime createdAt, final LocalDateTime lastLogin) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.college = college;
        this.branch = branch;
        this.gradYear = gradYear;
        this.primaryGoal = primaryGoal;
        this.problemsSolved = problemsSolved;
        this.currentStreak = currentStreak;
        this.bestStreak = bestStreak;
        this.xp = xp;
        this.level = level;
        this.league = league;
        this.globalRank = globalRank;
        this.createdAt = createdAt;
        this.lastLogin = lastLogin;
    }
}
