// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.controller;

import com.placementos.backend.dto.*;
import com.placementos.backend.service.AuthService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
public class AuthController {
    private final AuthService authService;

    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest req) {
        return ResponseEntity.ok(authService.register(req));
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest req) {
        return ResponseEntity.ok(authService.login(req));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthController(final AuthService authService) {
        this.authService = authService;
    }
}
