// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.controller;

import com.placementos.backend.dto.*;
import com.placementos.backend.service.AuthService;
import jakarta.validation.Valid;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
@CrossOrigin(
        originPatterns = {"https://crackplacement.vercel.app", "https://*.vercel.app", "http://localhost:5173", "http://localhost:3000"},
        allowCredentials = "true",
        allowedHeaders = "*",
        methods = {RequestMethod.POST, RequestMethod.OPTIONS}
)
public class AuthController {
    private final AuthService authService;

    @RequestMapping(value = {"/login", "/register"}, method = RequestMethod.OPTIONS)
    public ResponseEntity<Void> authPreflight() {
        HttpHeaders headers = new HttpHeaders();
        headers.add(HttpHeaders.ALLOW, "POST,OPTIONS");
        return new ResponseEntity<>(headers, HttpStatus.OK);
    }

    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest req) {
        return ResponseEntity.ok(authService.register(req));
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest req) {
        return ResponseEntity.ok(authService.login(req));
    }

    @PostMapping("/google")
    public ResponseEntity<AuthResponse> google(@Valid @RequestBody GoogleAuthRequest req) {
        return ResponseEntity.ok(authService.googleSignIn(req.getCredential()));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthController(final AuthService authService) {
        this.authService = authService;
    }
}
