
// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.controller;

import com.placementos.backend.dto.CodeExecutionRequest;
import com.placementos.backend.dto.CodeExecutionResponse;
import com.placementos.backend.service.CodeExecutionService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/execute")
public class CodeExecutionController {
    private final CodeExecutionService codeExecutionService;

    @PostMapping
    public ResponseEntity<CodeExecutionResponse> executeCode(@RequestBody CodeExecutionRequest request) {
        return ResponseEntity.ok(codeExecutionService.execute(request));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeExecutionController(final CodeExecutionService codeExecutionService) {
        this.codeExecutionService = codeExecutionService;
    }
}
