// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.controller;

import com.placementos.backend.entity.Job;
import com.placementos.backend.repository.JobRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/jobs")
public class JobController {
    private final JobRepository jobRepository;

    @GetMapping
    public ResponseEntity<List<Job>> getAll(@RequestParam(required = false) String type) {
        if (type != null) {
            return ResponseEntity.ok(jobRepository.findByType(Job.JobType.valueOf(type)));
        }
        return ResponseEntity.ok(jobRepository.findAll());
    }

    @GetMapping("/new")
    public ResponseEntity<List<Job>> getNew() {
        return ResponseEntity.ok(jobRepository.findByIsNewTrue());
    }

    @PostMapping
    public ResponseEntity<Job> create(@RequestBody Job job) {
        return ResponseEntity.ok(jobRepository.save(job));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public JobController(final JobRepository jobRepository) {
        this.jobRepository = jobRepository;
    }
}
