// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.controller;

import com.placementos.backend.entity.MockInterview;
import com.placementos.backend.repository.MockInterviewRepository;
import com.placementos.backend.entity.User;
import com.placementos.backend.repository.UserRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/interviews/mock")
public class MockInterviewController {
    private final MockInterviewRepository repo;
    private final UserRepository userRepository;

    @GetMapping("/my-interviews")
    public ResponseEntity<List<MockInterview>> getMyInterviews(Authentication auth) {
        User user = userRepository.findByEmail(auth.getName()).orElseThrow();
        return ResponseEntity.ok(repo.findByIntervieweeId(user.getId()));
    }

    @PostMapping("/schedule")
    public ResponseEntity<MockInterview> schedule(@RequestBody MockInterview mock, Authentication auth) {
        User user = userRepository.findByEmail(auth.getName()).orElseThrow();
        mock.setInterviewee(user);
        mock.setStatus(MockInterview.InterviewStatus.Scheduled);
        return ResponseEntity.ok(repo.save(mock));
    }

    @PutMapping("/{id}/status")
    public ResponseEntity<MockInterview> updateStatus(@PathVariable Long id, @RequestParam MockInterview.InterviewStatus status) {
        MockInterview mock = repo.findById(id).orElseThrow();
        mock.setStatus(status);
        return ResponseEntity.ok(repo.save(mock));
    }

    @PutMapping("/{id}/feedback")
    public ResponseEntity<MockInterview> updateFeedback(@PathVariable Long id, @RequestBody Map<String, Object> feedbackData) {
        MockInterview mock = repo.findById(id).orElseThrow();
        if (feedbackData.containsKey("feedback")) mock.setFeedback((String) feedbackData.get("feedback"));
        if (feedbackData.containsKey("strengths")) mock.setStrengths((String) feedbackData.get("strengths"));
        if (feedbackData.containsKey("improvements")) mock.setImprovements((String) feedbackData.get("improvements"));
        if (feedbackData.containsKey("rating")) mock.setRating((Integer) feedbackData.get("rating"));
        mock.setStatus(MockInterview.InterviewStatus.Completed);
        return ResponseEntity.ok(repo.save(mock));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MockInterviewController(final MockInterviewRepository repo, final UserRepository userRepository) {
        this.repo = repo;
        this.userRepository = userRepository;
    }
}
