// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.controller;

import com.placementos.backend.entity.User;
import com.placementos.backend.repository.UserRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.LinkedHashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/profile")
public class UserProfileController {
    private final UserRepository userRepository;

    @GetMapping
    public ResponseEntity<User> getProfile(Authentication auth) {
        return userRepository.findByEmail(auth.getName()).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());
    }

    @PutMapping
    public ResponseEntity<User> updateProfile(@RequestBody User profile, Authentication auth) {
        User user = userRepository.findByEmail(auth.getName()).orElseThrow();
        user.setFirstName(profile.getFirstName());
        user.setLastName(profile.getLastName());
        user.setCollege(profile.getCollege());
        user.setBranch(profile.getBranch());
        user.setGradYear(profile.getGradYear());
        user.setPrimaryGoal(profile.getPrimaryGoal());
        return ResponseEntity.ok(userRepository.save(user));
    }

    @PostMapping("/check-in")
    public ResponseEntity<Map<String, Object>> dailyCheckIn(Authentication auth) {
        User user = userRepository.findByEmail(auth.getName()).orElseThrow();

        LocalDate today = LocalDate.now();
        LocalDate lastCheckInDate = user.getLastLogin() == null ? null : user.getLastLogin().toLocalDate();

        boolean alreadyCheckedIn = today.equals(lastCheckInDate);
        if (!alreadyCheckedIn) {
            if (lastCheckInDate != null && ChronoUnit.DAYS.between(lastCheckInDate, today) == 1) {
                user.setCurrentStreak(user.getCurrentStreak() + 1);
            } else {
                user.setCurrentStreak(1);
            }

            user.setBestStreak(Math.max(user.getBestStreak(), user.getCurrentStreak()));
            user.setXp(user.getXp() + 10);
            user.setLastLogin(java.time.LocalDateTime.now());
            userRepository.save(user);
        }

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("alreadyCheckedIn", alreadyCheckedIn);
        response.put("currentStreak", user.getCurrentStreak());
        response.put("bestStreak", user.getBestStreak());
        response.put("xp", user.getXp());
        response.put("level", user.getLevel());
        return ResponseEntity.ok(response);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserProfileController(final UserRepository userRepository) {
        this.userRepository = userRepository;
    }
}
