// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.dto;

public class AuthResponse {
    private String token;
    private String email;
    private String firstName;
    private String lastName;
    private int xp;
    private int level;
    private String league;
    private int currentStreak;
    private int problemsSolved;
    private int globalRank;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getToken() {
        return this.token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getXp() {
        return this.xp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getLevel() {
        return this.level;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLeague() {
        return this.league;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCurrentStreak() {
        return this.currentStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getProblemsSolved() {
        return this.problemsSolved;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getGlobalRank() {
        return this.globalRank;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setXp(final int xp) {
        this.xp = xp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLevel(final int level) {
        this.level = level;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLeague(final String league) {
        this.league = league;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentStreak(final int currentStreak) {
        this.currentStreak = currentStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProblemsSolved(final int problemsSolved) {
        this.problemsSolved = problemsSolved;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGlobalRank(final int globalRank) {
        this.globalRank = globalRank;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthResponse)) return false;
        final AuthResponse other = (AuthResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getXp() != other.getXp()) return false;
        if (this.getLevel() != other.getLevel()) return false;
        if (this.getCurrentStreak() != other.getCurrentStreak()) return false;
        if (this.getProblemsSolved() != other.getProblemsSolved()) return false;
        if (this.getGlobalRank() != other.getGlobalRank()) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$league = this.getLeague();
        final java.lang.Object other$league = other.getLeague();
        if (this$league == null ? other$league != null : !this$league.equals(other$league)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getXp();
        result = result * PRIME + this.getLevel();
        result = result * PRIME + this.getCurrentStreak();
        result = result * PRIME + this.getProblemsSolved();
        result = result * PRIME + this.getGlobalRank();
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $league = this.getLeague();
        result = result * PRIME + ($league == null ? 43 : $league.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AuthResponse(token=" + this.getToken() + ", email=" + this.getEmail() + ", firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", xp=" + this.getXp() + ", level=" + this.getLevel() + ", league=" + this.getLeague() + ", currentStreak=" + this.getCurrentStreak() + ", problemsSolved=" + this.getProblemsSolved() + ", globalRank=" + this.getGlobalRank() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthResponse(final String token, final String email, final String firstName, final String lastName, final int xp, final int level, final String league, final int currentStreak, final int problemsSolved, final int globalRank) {
        this.token = token;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.xp = xp;
        this.level = level;
        this.league = league;
        this.currentStreak = currentStreak;
        this.problemsSolved = problemsSolved;
        this.globalRank = globalRank;
    }
}
