// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.dto;

public class CodeExecutionResponse {
    private String status; // "Accepted", "Compile Error", "Runtime Error", "Time Limit Exceeded"
    private String stdout; // printed output
    private String stderr; // error logs
    private String executionTime; // "12ms"


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CodeExecutionResponseBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String stdout;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String stderr;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String executionTime;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CodeExecutionResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CodeExecutionResponse.CodeExecutionResponseBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CodeExecutionResponse.CodeExecutionResponseBuilder stdout(final String stdout) {
            this.stdout = stdout;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CodeExecutionResponse.CodeExecutionResponseBuilder stderr(final String stderr) {
            this.stderr = stderr;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CodeExecutionResponse.CodeExecutionResponseBuilder executionTime(final String executionTime) {
            this.executionTime = executionTime;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CodeExecutionResponse build() {
            return new CodeExecutionResponse(this.status, this.stdout, this.stderr, this.executionTime);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CodeExecutionResponse.CodeExecutionResponseBuilder(status=" + this.status + ", stdout=" + this.stdout + ", stderr=" + this.stderr + ", executionTime=" + this.executionTime + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CodeExecutionResponse.CodeExecutionResponseBuilder builder() {
        return new CodeExecutionResponse.CodeExecutionResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStdout() {
        return this.stdout;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStderr() {
        return this.stderr;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getExecutionTime() {
        return this.executionTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStdout(final String stdout) {
        this.stdout = stdout;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStderr(final String stderr) {
        this.stderr = stderr;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExecutionTime(final String executionTime) {
        this.executionTime = executionTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CodeExecutionResponse)) return false;
        final CodeExecutionResponse other = (CodeExecutionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$stdout = this.getStdout();
        final java.lang.Object other$stdout = other.getStdout();
        if (this$stdout == null ? other$stdout != null : !this$stdout.equals(other$stdout)) return false;
        final java.lang.Object this$stderr = this.getStderr();
        final java.lang.Object other$stderr = other.getStderr();
        if (this$stderr == null ? other$stderr != null : !this$stderr.equals(other$stderr)) return false;
        final java.lang.Object this$executionTime = this.getExecutionTime();
        final java.lang.Object other$executionTime = other.getExecutionTime();
        if (this$executionTime == null ? other$executionTime != null : !this$executionTime.equals(other$executionTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CodeExecutionResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $stdout = this.getStdout();
        result = result * PRIME + ($stdout == null ? 43 : $stdout.hashCode());
        final java.lang.Object $stderr = this.getStderr();
        result = result * PRIME + ($stderr == null ? 43 : $stderr.hashCode());
        final java.lang.Object $executionTime = this.getExecutionTime();
        result = result * PRIME + ($executionTime == null ? 43 : $executionTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CodeExecutionResponse(status=" + this.getStatus() + ", stdout=" + this.getStdout() + ", stderr=" + this.getStderr() + ", executionTime=" + this.getExecutionTime() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeExecutionResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeExecutionResponse(final String status, final String stdout, final String stderr, final String executionTime) {
        this.status = status;
        this.stdout = stdout;
        this.stderr = stderr;
        this.executionTime = executionTime;
    }
}
