// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.dto;

public class CodeExecutionRequest {
    private String language; // "java", "python", "cpp", "js"
    private String code; // The finalized runnable code string containing main()

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeExecutionRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLanguage() {
        return this.language;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLanguage(final String language) {
        this.language = language;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CodeExecutionRequest)) return false;
        final CodeExecutionRequest other = (CodeExecutionRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$language = this.getLanguage();
        final java.lang.Object other$language = other.getLanguage();
        if (this$language == null ? other$language != null : !this$language.equals(other$language)) return false;
        final java.lang.Object this$code = this.getCode();
        final java.lang.Object other$code = other.getCode();
        if (this$code == null ? other$code != null : !this$code.equals(other$code)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CodeExecutionRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $language = this.getLanguage();
        result = result * PRIME + ($language == null ? 43 : $language.hashCode());
        final java.lang.Object $code = this.getCode();
        result = result * PRIME + ($code == null ? 43 : $code.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CodeExecutionRequest(language=" + this.getLanguage() + ", code=" + this.getCode() + ")";
    }
}
