// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.dto;

import jakarta.validation.constraints.NotNull;

public class PracticeProgressUpdateRequest {
    @NotNull
    private Boolean completed;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PracticeProgressUpdateRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getCompleted() {
        return this.completed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompleted(final Boolean completed) {
        this.completed = completed;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PracticeProgressUpdateRequest)) return false;
        final PracticeProgressUpdateRequest other = (PracticeProgressUpdateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$completed = this.getCompleted();
        final java.lang.Object other$completed = other.getCompleted();
        if (this$completed == null ? other$completed != null : !this$completed.equals(other$completed)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PracticeProgressUpdateRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $completed = this.getCompleted();
        result = result * PRIME + ($completed == null ? 43 : $completed.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PracticeProgressUpdateRequest(completed=" + this.getCompleted() + ")";
    }
}
