// Generated by delombok at Tue Mar 31 23:02:23 IST 2026
package com.placementos.backend.dto;

import jakarta.validation.constraints.*;

public class RegisterRequest {
    @NotBlank
    private String firstName;
    @NotBlank
    private String lastName;
    @Email
    @NotBlank
    private String email;
    @Size(min = 8)
    @NotBlank
    private String password;
    private String college;
    private String branch;
    private String gradYear;
    private String primaryGoal;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RegisterRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCollege() {
        return this.college;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBranch() {
        return this.branch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGradYear() {
        return this.gradYear;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPrimaryGoal() {
        return this.primaryGoal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCollege(final String college) {
        this.college = college;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBranch(final String branch) {
        this.branch = branch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGradYear(final String gradYear) {
        this.gradYear = gradYear;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrimaryGoal(final String primaryGoal) {
        this.primaryGoal = primaryGoal;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RegisterRequest)) return false;
        final RegisterRequest other = (RegisterRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$college = this.getCollege();
        final java.lang.Object other$college = other.getCollege();
        if (this$college == null ? other$college != null : !this$college.equals(other$college)) return false;
        final java.lang.Object this$branch = this.getBranch();
        final java.lang.Object other$branch = other.getBranch();
        if (this$branch == null ? other$branch != null : !this$branch.equals(other$branch)) return false;
        final java.lang.Object this$gradYear = this.getGradYear();
        final java.lang.Object other$gradYear = other.getGradYear();
        if (this$gradYear == null ? other$gradYear != null : !this$gradYear.equals(other$gradYear)) return false;
        final java.lang.Object this$primaryGoal = this.getPrimaryGoal();
        final java.lang.Object other$primaryGoal = other.getPrimaryGoal();
        if (this$primaryGoal == null ? other$primaryGoal != null : !this$primaryGoal.equals(other$primaryGoal)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RegisterRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $college = this.getCollege();
        result = result * PRIME + ($college == null ? 43 : $college.hashCode());
        final java.lang.Object $branch = this.getBranch();
        result = result * PRIME + ($branch == null ? 43 : $branch.hashCode());
        final java.lang.Object $gradYear = this.getGradYear();
        result = result * PRIME + ($gradYear == null ? 43 : $gradYear.hashCode());
        final java.lang.Object $primaryGoal = this.getPrimaryGoal();
        result = result * PRIME + ($primaryGoal == null ? 43 : $primaryGoal.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "RegisterRequest(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", college=" + this.getCollege() + ", branch=" + this.getBranch() + ", gradYear=" + this.getGradYear() + ", primaryGoal=" + this.getPrimaryGoal() + ")";
    }
}
